/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_LSOC_PB_H_INCLUDED
#define PB_LSOC_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Domain {
    Domain_APP = 0,
    Domain_SYS = 1,
    Domain_NET = 2
} Domain;

typedef enum _Code {
    Code_INF = 0,
    Code_ATS = 1,
    Code_MES = 2,
    Code_UPT = 3,
    Code_ACC = 4
} Code;

typedef enum _AtsCmdData_Type {
    AtsCmdData_Type_FULL = 0,
    AtsCmdData_Type_FILE = 1,
    AtsCmdData_Type_LIBRARY = 2,
    AtsCmdData_Type_NET = 3,
    AtsCmdData_Type_DEV = 5
} AtsCmdData_Type;

typedef enum _MesCmdData_Type {
    MesCmdData_Type_FULL = 0,
    MesCmdData_Type_FILE = 1,
    MesCmdData_Type_NET = 3
} MesCmdData_Type;

typedef enum _UptCmdData_Type {
    UptCmdData_Type_POLICY = 0,
    UptCmdData_Type_SESSION = 4
} UptCmdData_Type;

/* Struct definitions */
typedef struct _InfData {
    das_pb_callback_t version;
    das_pb_callback_t device;
    das_pb_callback_t state;
} InfData;

typedef struct _AtsCmdData {
    AtsCmdData_Type type;
    das_pb_callback_t patternUrl;
    das_pb_callback_t pattern;
} AtsCmdData;

typedef struct _AtsDevData {
    uint64_t cmd;
    das_pb_callback_t object;
} AtsDevData;

typedef struct _AtsEndData {
    uint64_t cmd;
    uint32_t total;
    das_pb_callback_t sum;
} AtsEndData;

typedef struct _AtsFilData {
    uint64_t cmd;
    das_pb_callback_t path;
    das_pb_callback_t attribute;
    das_pb_callback_t signature;
} AtsFilData;

typedef struct _AtsNetData {
    uint64_t cmd;
} AtsNetData;

typedef struct _AtsSysData {
    uint64_t cmd;
} AtsSysData;

typedef struct _MesCmdData {
    MesCmdData_Type type;
} MesCmdData;

typedef struct _MesEndData {
    uint64_t cmd;
    uint32_t total;
} MesEndData;

typedef struct _MesFilData {
    uint64_t cmd;
    das_pb_callback_t sum;
    das_pb_callback_t mac;
} MesFilData;

typedef struct _MesNetData {
    uint64_t cmd;
    das_pb_callback_t sum;
    das_pb_callback_t mac;
} MesNetData;

typedef struct _UptCmdData {
    UptCmdData_Type type;
    das_pb_callback_t url;
    das_pb_callback_t object;
} UptCmdData;

typedef struct _Message {
    Domain domain;
    Code code;
    uint64_t timestamp;
    das_pb_callback_t cb_data;
    das_pb_size_t which_data;
    union {
        InfData infData;
        AtsCmdData atsCmdData;
        AtsEndData atsEndData;
        AtsFilData atsFilData;
        AtsDevData atsDevData;
        MesCmdData mesCmdData;
        MesEndData mesEndData;
        MesFilData mesFilData;
        UptCmdData uptCmdData;
    } data;
    das_pb_callback_t session;
} Message;


/* Helper constants for enums */
#define _Domain_MIN Domain_APP
#define _Domain_MAX Domain_NET
#define _Domain_ARRAYSIZE ((Domain)(Domain_NET+1))

#define _Code_MIN Code_INF
#define _Code_MAX Code_ACC
#define _Code_ARRAYSIZE ((Code)(Code_ACC+1))

#define _AtsCmdData_Type_MIN AtsCmdData_Type_FULL
#define _AtsCmdData_Type_MAX AtsCmdData_Type_DEV
#define _AtsCmdData_Type_ARRAYSIZE ((AtsCmdData_Type)(AtsCmdData_Type_DEV+1))

#define _MesCmdData_Type_MIN MesCmdData_Type_FULL
#define _MesCmdData_Type_MAX MesCmdData_Type_NET
#define _MesCmdData_Type_ARRAYSIZE ((MesCmdData_Type)(MesCmdData_Type_NET+1))

#define _UptCmdData_Type_MIN UptCmdData_Type_POLICY
#define _UptCmdData_Type_MAX UptCmdData_Type_SESSION
#define _UptCmdData_Type_ARRAYSIZE ((UptCmdData_Type)(UptCmdData_Type_SESSION+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define InfData_init_default                     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define AtsCmdData_init_default                  {_AtsCmdData_Type_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define AtsFilData_init_default                  {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define AtsNetData_init_default                  {0}
#define AtsSysData_init_default                  {0}
#define AtsDevData_init_default                  {0, {{NULL}, NULL}}
#define AtsEndData_init_default                  {0, 0, {{NULL}, NULL}}
#define MesCmdData_init_default                  {_MesCmdData_Type_MIN}
#define MesFilData_init_default                  {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define MesNetData_init_default                  {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define MesEndData_init_default                  {0, 0}
#define UptCmdData_init_default                  {_UptCmdData_Type_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define Message_init_default                     {_Domain_MIN, _Code_MIN, 0, {{NULL}, NULL}, 0, {InfData_init_default}, {{NULL}, NULL}}
#define InfData_init_zero                        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define AtsCmdData_init_zero                     {_AtsCmdData_Type_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define AtsFilData_init_zero                     {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define AtsNetData_init_zero                     {0}
#define AtsSysData_init_zero                     {0}
#define AtsDevData_init_zero                     {0, {{NULL}, NULL}}
#define AtsEndData_init_zero                     {0, 0, {{NULL}, NULL}}
#define MesCmdData_init_zero                     {_MesCmdData_Type_MIN}
#define MesFilData_init_zero                     {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define MesNetData_init_zero                     {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define MesEndData_init_zero                     {0, 0}
#define UptCmdData_init_zero                     {_UptCmdData_Type_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define Message_init_zero                        {_Domain_MIN, _Code_MIN, 0, {{NULL}, NULL}, 0, {InfData_init_zero}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define InfData_version_tag                      1
#define InfData_device_tag                       2
#define InfData_state_tag                        3
#define AtsCmdData_type_tag                      1
#define AtsCmdData_patternUrl_tag                2
#define AtsCmdData_pattern_tag                   3
#define AtsDevData_cmd_tag                       1
#define AtsDevData_object_tag                    2
#define AtsEndData_cmd_tag                       1
#define AtsEndData_total_tag                     2
#define AtsEndData_sum_tag                       3
#define AtsFilData_cmd_tag                       1
#define AtsFilData_path_tag                      2
#define AtsFilData_attribute_tag                 3
#define AtsFilData_signature_tag                 4
#define AtsNetData_cmd_tag                       1
#define AtsSysData_cmd_tag                       1
#define MesCmdData_type_tag                      1
#define MesEndData_cmd_tag                       1
#define MesEndData_total_tag                     2
#define MesFilData_cmd_tag                       1
#define MesFilData_sum_tag                       2
#define MesFilData_mac_tag                       3
#define MesNetData_cmd_tag                       1
#define MesNetData_sum_tag                       2
#define MesNetData_mac_tag                       3
#define UptCmdData_type_tag                      1
#define UptCmdData_url_tag                       2
#define UptCmdData_object_tag                    3
#define Message_domain_tag                       1
#define Message_code_tag                         2
#define Message_timestamp_tag                    3
#define Message_infData_tag                      4
#define Message_atsCmdData_tag                   5
#define Message_atsEndData_tag                   6
#define Message_atsFilData_tag                   7
#define Message_atsDevData_tag                   10
#define Message_mesCmdData_tag                   11
#define Message_mesEndData_tag                   12
#define Message_mesFilData_tag                   13
#define Message_uptCmdData_tag                   32
#define Message_session_tag                      254

/* Struct field encoding specification for nanopb */
#define InfData_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   version,           1) \
X(a, CALLBACK, SINGULAR, STRING,   device,            2) \
X(a, CALLBACK, SINGULAR, STRING,   state,             3)
#define InfData_CALLBACK das_pb_default_field_callback
#define InfData_DEFAULT NULL

#define AtsCmdData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, SINGULAR, STRING,   patternUrl,        2) \
X(a, CALLBACK, SINGULAR, STRING,   pattern,           3)
#define AtsCmdData_CALLBACK das_pb_default_field_callback
#define AtsCmdData_DEFAULT NULL

#define AtsFilData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   cmd,               1) \
X(a, CALLBACK, SINGULAR, STRING,   path,              2) \
X(a, CALLBACK, SINGULAR, STRING,   attribute,         3) \
X(a, CALLBACK, SINGULAR, STRING,   signature,         4)
#define AtsFilData_CALLBACK das_pb_default_field_callback
#define AtsFilData_DEFAULT NULL

#define AtsNetData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   cmd,               1)
#define AtsNetData_CALLBACK NULL
#define AtsNetData_DEFAULT NULL

#define AtsSysData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   cmd,               1)
#define AtsSysData_CALLBACK NULL
#define AtsSysData_DEFAULT NULL

#define AtsDevData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   cmd,               1) \
X(a, CALLBACK, SINGULAR, STRING,   object,            2)
#define AtsDevData_CALLBACK das_pb_default_field_callback
#define AtsDevData_DEFAULT NULL

#define AtsEndData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   cmd,               1) \
X(a, STATIC,   SINGULAR, UINT32,   total,             2) \
X(a, CALLBACK, SINGULAR, STRING,   sum,               3)
#define AtsEndData_CALLBACK das_pb_default_field_callback
#define AtsEndData_DEFAULT NULL

#define MesCmdData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1)
#define MesCmdData_CALLBACK NULL
#define MesCmdData_DEFAULT NULL

#define MesFilData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   cmd,               1) \
X(a, CALLBACK, SINGULAR, STRING,   sum,               2) \
X(a, CALLBACK, SINGULAR, STRING,   mac,               3)
#define MesFilData_CALLBACK das_pb_default_field_callback
#define MesFilData_DEFAULT NULL

#define MesNetData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   cmd,               1) \
X(a, CALLBACK, SINGULAR, STRING,   sum,               2) \
X(a, CALLBACK, SINGULAR, STRING,   mac,               3)
#define MesNetData_CALLBACK das_pb_default_field_callback
#define MesNetData_DEFAULT NULL

#define MesEndData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   cmd,               1) \
X(a, STATIC,   SINGULAR, UINT32,   total,             2)
#define MesEndData_CALLBACK NULL
#define MesEndData_DEFAULT NULL

#define UptCmdData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, SINGULAR, STRING,   url,               2) \
X(a, CALLBACK, SINGULAR, STRING,   object,            3)
#define UptCmdData_CALLBACK das_pb_default_field_callback
#define UptCmdData_DEFAULT NULL

#define Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    domain,            1) \
X(a, STATIC,   SINGULAR, UENUM,    code,              2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         3) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (data,infData,data.infData),   4) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (data,atsCmdData,data.atsCmdData),   5) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (data,atsEndData,data.atsEndData),   6) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (data,atsFilData,data.atsFilData),   7) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (data,atsDevData,data.atsDevData),  10) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (data,mesCmdData,data.mesCmdData),  11) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (data,mesEndData,data.mesEndData),  12) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (data,mesFilData,data.mesFilData),  13) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (data,uptCmdData,data.uptCmdData),  32) \
X(a, CALLBACK, SINGULAR, STRING,   session,         254)
#define Message_CALLBACK das_pb_default_field_callback
#define Message_DEFAULT NULL
#define Message_data_infData_MSGTYPE InfData
#define Message_data_atsCmdData_MSGTYPE AtsCmdData
#define Message_data_atsEndData_MSGTYPE AtsEndData
#define Message_data_atsFilData_MSGTYPE AtsFilData
#define Message_data_atsDevData_MSGTYPE AtsDevData
#define Message_data_mesCmdData_MSGTYPE MesCmdData
#define Message_data_mesEndData_MSGTYPE MesEndData
#define Message_data_mesFilData_MSGTYPE MesFilData
#define Message_data_uptCmdData_MSGTYPE UptCmdData

extern const das_pb_msgdesc_t InfData_msg;
extern const das_pb_msgdesc_t AtsCmdData_msg;
extern const das_pb_msgdesc_t AtsFilData_msg;
extern const das_pb_msgdesc_t AtsNetData_msg;
extern const das_pb_msgdesc_t AtsSysData_msg;
extern const das_pb_msgdesc_t AtsDevData_msg;
extern const das_pb_msgdesc_t AtsEndData_msg;
extern const das_pb_msgdesc_t MesCmdData_msg;
extern const das_pb_msgdesc_t MesFilData_msg;
extern const das_pb_msgdesc_t MesNetData_msg;
extern const das_pb_msgdesc_t MesEndData_msg;
extern const das_pb_msgdesc_t UptCmdData_msg;
extern const das_pb_msgdesc_t Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define InfData_fields &InfData_msg
#define AtsCmdData_fields &AtsCmdData_msg
#define AtsFilData_fields &AtsFilData_msg
#define AtsNetData_fields &AtsNetData_msg
#define AtsSysData_fields &AtsSysData_msg
#define AtsDevData_fields &AtsDevData_msg
#define AtsEndData_fields &AtsEndData_msg
#define MesCmdData_fields &MesCmdData_msg
#define MesFilData_fields &MesFilData_msg
#define MesNetData_fields &MesNetData_msg
#define MesEndData_fields &MesEndData_msg
#define UptCmdData_fields &UptCmdData_msg
#define Message_fields &Message_msg

/* Maximum encoded size of messages (where known) */
/* InfData_size depends on runtime parameters */
/* AtsCmdData_size depends on runtime parameters */
/* AtsFilData_size depends on runtime parameters */
#define AtsNetData_size                          11
#define AtsSysData_size                          11
/* AtsDevData_size depends on runtime parameters */
/* AtsEndData_size depends on runtime parameters */
#define MesCmdData_size                          2
/* MesFilData_size depends on runtime parameters */
/* MesNetData_size depends on runtime parameters */
#define MesEndData_size                          17
/* UptCmdData_size depends on runtime parameters */
/* Message_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
