/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "lsoc_pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(InfData, InfData, AUTO)


PB_BIND(AtsCmdData, AtsCmdData, AUTO)


PB_BIND(AtsFilData, AtsFilData, AUTO)


PB_BIND(AtsNetData, AtsNetData, AUTO)


PB_BIND(AtsSysData, AtsSysData, AUTO)


PB_BIND(AtsDevData, AtsDevData, AUTO)


PB_BIND(AtsEndData, AtsEndData, AUTO)


PB_BIND(MesCmdData, MesCmdData, AUTO)


PB_BIND(MesFilData, MesFilData, AUTO)


PB_BIND(MesNetData, MesNetData, AUTO)


PB_BIND(MesEndData, MesEndData, AUTO)


PB_BIND(UptCmdData, UptCmdData, AUTO)


PB_BIND(Message, Message, 2)








