; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
board_1m = esp01
ldscript_1m = eagle.flash.1m192.ld
workspace = D:/Project/irext/iris-kit

[env]
platform = espressif8266
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM5
monitor_port = COM5
board_build.flash_mode = dout
build_flags =
    -Wno-unused-function
    -Wno-unused-variable
    -DLOG_DEBUG=1
    -DLOG_INFO=1
    -DLOG_ERROR=1
    -I${common.workspace}/lib/IRext/include

[env:esp8266-1m-base]
board = ${common.board_1m}
board_build.ldscript = ${common.ldscript_1m}
lib_deps = rweather/Crypto@^0.2.0
