; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
board_1m = esp01_1m
ldscript_1m = eagle.flash.1m64.ld
workspace = ${HOME}/Develop/project/irext/iris-kit

[env]
platform = espressif8266
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
board_build.flash_mode = dout
build_flags =
	-Wno-unused-function
	-Wno-unused-variable
	-DLOG_DEBUG=1
	-DLOG_INFO=1
	-DLOG_ERROR=1
	-DSTORE_RECEIVED_IR_DATA=1
extra_scripts = post:rename_firmware.py
lib_deps =
    wnatth3/WiFiManager@2.0.16-rc.2

[env:esp8266-1m-irext]
extends = env
board = ${common.board_1m}
board_build.ldscript = ${common.ldscript_1m}
build_flags =
	${env.build_flags}
	-DIRIS_KIT_IREXT=1
	-DFIRMWARE_RENAME=iris_kit_latest

[env:esp8266-1m-geeklink]
extends = env
board = ${common.board_1m}
board_build.ldscript = ${common.ldscript_1m}
build_flags =
	${env.build_flags}
	-DIRIS_KIT_GEEKLINK=1
	-DFIRMWARE_RENAME=iris_kit_geeklink_latest